### ISSUE TITLE
Segment splitting view

### ISSUE THREAD

**Issue by sobri909** [sobri909/ArcMini#32]
## Todos

- [x] On return from left/right type change view, only one segment shows on map
- [x] On return to segment view, after "Done", map isn't updated
- [x] Tapping "Done" should go two steps back, to details view, not segment edit view
- [x] Change Type view needs to show both path line and circle if segment is stationary type
